### ISSUE TITLE
Add args to start & test scripts

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/pow-captcha#2]
# Overview

Adding parameters like `sqlite` or `mssql` (_default_) to the start scripts to specify the database engine the app is running on. Based on the argument, it should update the project & modify the dependencies then restore & build the project. By default, it should use the mssql db provider.

https://github.com/dan-koller/pow-captcha/blob/1ba4af26c7246ffe24d7ae21c805e59e84003023/start.sh

https://github.com/dan-koller/pow-captcha/blob/1ba4af26c7246ffe24d7ae21c805e59e84003023/start.bat

## Tasks

- [x] Add arguments to the script & use `mssql` by default
- [x] Modify dependencies based on the given parameter
- [x] Restore & build the solution
- [x] Run the projects
- [x] Build script for *NIX systems
- [x] Add a `-nolocals` flag to ignore local tests (like database connection) utilizing`dotnet test PowC.UnitTests/PowC.UnitTests.csproj --filter FullyQualifiedName!~PowC\.UnitTests\.DbConnectionTests\.`
- [x] Add a `-help` flag to view usage options and flags
- [x] Port shell script to batch or powershell for windows
- [x] Organize scripts in a `_Scripts` project
- [x] Enhance dependency replacement logic to reduce duplicate code

## Bugs

- [x] Running the script multiple times using the `sqlite` flag causes deformation of `.csproj` file
